CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
UNICODE_ENABLE = no

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LAYER_LOCK_ENABLE = yes
LEADER_ENABLE = yes
# TAP_DANCE_ENABLE = yes

LTO_ENABLE = yes
